/* DO NOT EDIT THIS FILE UNLESS YOU HAVE A SPECIFIC REASON TO!*/

/* This file is autoloaded on every html page and acts as a bootstrapper for your JS files.
   This script checks what page you're currently on and tries to find a matching script
   with the same filename with the .js extension. A warning is printed in the console
   in a dev environment only if no js file has been found.
*/

import "./autoload.js"

if (module.hot) {
    module.hot.accept();
  }
  if (!document.location.pathname.endsWith(".html")) {
    let newUrl = window.location.pathname;
    if (newUrl.charAt(newUrl.length - 1) !== "/") {
      newUrl += "/";
    }
    window.location.replace(`${newUrl}index.html`);
  }
  const location = document.location.pathname.split("/").pop().split(".");
  location.pop();
  const jsFile = location.join(".") + ".js";
  try {
    require(`./${jsFile}`);
  } catch (error) {
    if (process.env === "development") {
      console.warn("No JS module for", jsFile);
    }
  }